version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_django_news
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

volumes:
  mongodb_data:
    driver: local
